streetsidesoftware/vscode-spell-checker

client/README.md
- Fix spelling of file type names.
=> docs(README.md) fix spelling of file type names

pull-changes-from-upstream.sh
- Add tool to merge latest changes from the upstream Git repository
This is a relatively simple thing, but I keep forgetting the steps all the time.
Adding this to the Git repository would make it easier for people to contribute to the project.
_More details from the GitHub User Documentation:_
- [Configuring a remote for a fork](https://help.github.com/articles/configuring-a-remote-for-a-fork/)
- [Syncing a fork](https://help.github.com/articles/syncing-a-fork/)
=> feat(pull-changes-from-upstream.sh) new tool

client/src/statusbar.ts
=> Remove `sbCheck.color` assignment preventing theme foreground color changing

README.md
You're being too modest - this thing knows more than just Typescript and JavaScript!
Probably want to update the description line in your GitHub repo too.
=> Can spell check more than typescript and JavaScript

README.md, packages/client/README.md, packages/client/package.json
Thanks for making this spell checker. I was going through the readme to familiarise myself with the addon and noticed a few broken links which I thought I'd fix.
=> Fix links pointing at the client directory

.travis.yml, package.json, packages/client/npm-shrinkwrap.json
I recloned the repo and ran the client installation and build tasks, but the sources were failing to compile. Then I read `.travis.yml` and realized that lerna had to be run first. I would like to simplify this step, so that it's as simple as running `npm i` in the root directory. Then I only have to worry about building the client package.
I'm trying to get this extension working on [code-server](https://github.com/codercom/code-server) (related: codercom/code-server#63).
```
> code-spell-checker@1.7.0 build /tmp/vscode-spell-checker/packages/client
> tsc -p ./
src/client/client.ts(9,5): error TS2305: Module '"../server"' has no exported member 'GetConfigurationForDocumentResult'.
src/client/client.ts(10,5): error TS2305: Module '"../server"' has no exported member 'NotifyServerMethods'. …
```
=> Combine lerna setup with initial install to allow for automation

packages/_server/npm-shrinkwrap.json, packages/_server/package.json
=> Update cspell-glob to address ignore files on Windows

packages/_server/.vscode/cSpell.json, packages/_server/.vscode/settings.json, packages/_server/npm-shrinkwrap.json, packages/_server/package.json, packages/_server/src/codeActions.ts, packages/_server/src/server.ts, packages/client/npm-shrinkwrap.json, packages/client/package.json
=> fix: Upgrade to vscode-languageserver 6

packages/client/README.md
I updated the list of available add-on dictionaries on the client README.md in order to include all currently available ones.
=> Updated list of available add-on dictionaries

packages/client/package.json
=> Ignore vscode-insiders dir

cspell-words.txt, packages/_server/src/PatternMatcher.ts, packages/_server/src/server.ts, packages/client/package.json, packages/client/src/extensionRegEx/RegexpOutlineProvider.ts, packages/client/src/extensionRegEx/extensionRegEx.ts
=> fix: Issues relating to the RegExp Tester

cSpell.json, packages/_server/package-lock.json, packages/_server/package.json, packages/_server/src/server.ts, packages/client/package.json, samples/bad-imports/README.md, samples/bad-imports/cspell.json
=> fix: Fix crash with missing import

packages/_server/package-lock.json, packages/_server/package.json, packages/_server/src/server.ts
Improved handling of missing config files.
=> ci: Update cspell-lib

packages/client/src/settings/CSpellSettings.ts
=> fix: issue with adding words to workspace.

.vscodeignore, cSpell.json, cspell-words.txt, fixtures/workspaces/js-config/README.md, fixtures/workspaces/js-config/cspell.config.js, fixtures/workspaces/js-config/custom-terms.txt, fixtures/workspaces/js-config/js-config.code-workspace, package.json, packages/_server/.vscode/launch.json, packages/_server/package.json, packages/_server/webpack.config.js, packages/client/package.json
- Do not WebPack `import-fresh`
=> fix: Support reading cspell.config.js files

package.json, packages/_integrationTests/package.json, packages/_server/package.json, packages/_server/src/config/cspellConfig.ts, packages/client/package.json, packages/client/src/statusbar.ts, yarn.lock
- Added configuration: `cSpell.showStatusAlignment`
- Fix: #949
- Make the status smaller and cleaner.
=> fix: Clean up the status bar

packages/_server/src/config/documentSettings.test.ts, packages/_server/src/config/documentSettings.ts, packages/client/src/infoViewer/infoView.ts, packages/client/src/settings/settings.ts, samples/code/example.f90, samples/cspell.json
=> fix: Support case sensitive file types

packages/_server/src/config/configTargets.test.ts, packages/_server/src/config/configTargets.ts, packages/_server/src/config/configTargetsHelper.test.ts, packages/_server/src/config/configTargetsHelper.ts, packages/_server/src/config/documentSettings.ts, packages/_server/src/utils/util.ts
Make sure they are sorted correctly.
=> dev: calculate config targets

cspell-words.txt, fixtures/workspaces/yarn2/yarn2-test-med/package.json, fixtures/workspaces/yarn2/yarn2-test-science/package.json, package.json, packages/___buildTools/src/updatePackageCSpellSchema.ts, packages/_integrationTests/package.json, packages/_server/package.json, packages/_server/spell-checker-config.schema.json, packages/_server/src/config/cspellConfig.ts, packages/_server/src/config/documentSettings.ts, packages/_serverPatternMatcher/package.json, packages/client/package.json, packages/client/src/settings/configFields.ts, yarn.lock
=> dev: Upgrade to `cspell 5.6.7`

CONTRIBUTE.md
=> "how to add configuration" tutorial in CONTRIBUTE

docs/_includes/generated-docs/configuration.md, package.json, packages/_server/spell-checker-config.schema.json, packages/_server/src/config/cspellConfig.ts
=> fix: check all files by default

packages/client/src/settings/__snapshots__/configFileReadWrite.test.ts.snap, packages/client/src/settings/configFileReadWrite.test.ts, packages/client/src/settings/configFileReadWrite.ts
=> fix: Always add a new line at the end of

.github/workflows/release.yml
[GH Release · Actions · GitHub Marketplace](https://github.com/marketplace/actions/gh-release)
=> ci: Update Release Action to use `softprops/action-gh-release`

packages/_server/src/api.ts, packages/_server/src/config/documentSettings.ts, packages/_server/src/server.ts, packages/_settingsViewer/src/api/settings/settings.ts, packages/_settingsViewer/src/test/samples/sampleSettings.ts, packages/_settingsViewer/src/test/samples/sampleWorkspace.ts, packages/_settingsViewer/src/viewer/components/__snapshots__/panelFile.test.tsx.snap, packages/_settingsViewer/src/viewer/components/link.tsx, packages/_settingsViewer/src/viewer/components/panelFile.tsx, packages/_settingsViewer/src/viewer/vsCodeTestWrapper.tsx, packages/_settingsViewer/webpack.dev.js, packages/client/package.json, packages/client/src/commands.ts, packages/client/src/infoViewer/infoHelper.ts, packages/client/src/util/uriHelper.ts, packages/package-json-dependency-updater/package.json, yarn.lock
=> fix: Improve handling of `.gitignore`

docs/_includes/generated-docs/configuration.md, package.json, packages/_integrationTests/package.json, packages/_server/package.json, packages/_server/spell-checker-config.schema.json, packages/_server/src/config/cspellConfig.ts, packages/_serverPatternMatcher/package.json, packages/client/package.json, packages/client/src/settings/languageIds.ts, yarn.lock
- cspell now bundles Swift and
=> dev: Add VUE to the default set of file types.

README.md, docs/index.md
Use uppercase "X" in word "LaTeX" when possible.
=> docs: s/LaTex/LaTeX/

packages/_server/src/SuggestionsGenerator.ts
=> fix: Make sure the suggestion limit is enforced.

packages/_server/src/clientApi.test.ts, packages/_server/src/config/documentSettings.test.ts, packages/_server/src/config/vscode.config.test.ts, packages/_server/src/progressNotifier.test.ts, packages/_server/src/validator.test.ts, packages/_settingsViewer/src/viewer/components/colors.test.ts, packages/client/src/autocomplete.test.ts, packages/client/src/diags.test.ts, packages/client/src/settings/DictionaryHelper.test.ts, packages/client/src/settings/configRepository.test.ts, packages/client/src/settings/configTargetHelper.test.ts, packages/client/src/settings/vsConfig.test.ts, packages/client/src/settings/vsConfigReaderWriter.test.ts, packages/jest-mock-vscode-examples/jest.config.js, packages/jest-mock-vscode-examples/package.json, packages/jest-mock-vscode-examples/src/__mocks__/vscode.js, packages/jest-mock-vscode-examples/src/workspace.test.ts, packages/jest-mock-vscode-examples/tsconfig.json, packages/jest-mock-vscode/LICENSE, packages/jest-mock-vscode/README.md, packages/jest-mock-vscode/package.json, packages/jest-mock-vscode/src/vscode/workspace.test.ts, packages/jest-mock-vscode/src/vscode/workspace.ts
- Add README
- Add LICENSE
- Add Examples
=> fix: Improve Jest Mock VSCode package

packages/client/src/settings/DictionaryHelper.test.ts, packages/client/src/settings/DictionaryHelper.ts
fix: #1671
- Add a fix
- Improve Unit Tests and coverage
=> fix: Remove words

docs/_includes/generated-docs/configuration.md, package.json, packages/__utils/src/index.ts, packages/__utils/src/logFile.ts, packages/__utils/src/logger.ts, packages/_server/.vscode/launch.json, packages/_server/spell-checker-config.schema.json, packages/_server/src/config/cspellConfig.ts, packages/_server/src/server.ts, packages/_server/src/utils/debounce.ts, packages/client/src/client/client.ts, packages/client/src/context.ts, packages/client/src/settings/configFields.ts, packages/client/src/statusbar.ts
Reduce the amount of handshaking between the client and server.
=> fix: Improve Extension performance

package.json, packages/_server/package.json, packages/_serverPatternMatcher/package.json, packages/_settingsViewer/package.json, packages/client/package.json, packages/package-json-dependency-updater/package.json, yarn.lock
=> ci: Update packages

cspell-words.txt, docs/_includes/generated-docs/configuration.md, package.json, packages/_server/spell-checker-config.schema.json, packages/_server/src/config/cspellConfig.ts, packages/_server/src/server.ts, packages/client/src/commands.ts, packages/client/src/settings/configFields.ts
=> fix: Add a workaround for issue with Markdown Rename

package.json
=> fix: Add Sponsor link

.github/workflows/integration-test.yml, .github/workflows/test.yml, azure-pipelines.yml, package.json
=> fix: Fix the needed VS Code version

README.md, fixtures/workspaces/dictionaries/remote/cspell.json, packages/__utils/src/uriHelper.test.ts, packages/__utils/src/uriHelper.ts, packages/_server/src/config/configTargetsHelper.ts, packages/_server/src/config/documentSettings.ts, packages/client/FAQ.md, packages/client/src/client/client.ts, packages/client/src/infoViewer/infoHelper.ts, packages/client/src/statusbar.ts, packages/client/src/util/uriHelper.ts
Correctly shows dictionaries with `http` sources.
=> fix: Address Issues with show the status of a file.

FAQ.md, README.md, cSpell.json, package.json, packages/_server/spell-checker-config.schema.json, packages/_server/src/config/cspellConfig.ts, packages/_server/src/config/customDictionaries.ts, packages/_server/src/config/documentSettings.ts, packages/_settingsViewer/CHANGELOG.md
=> fix: Show all possible dictionaries in codeAction

docs/_includes/generated-docs/configuration.md, package.json, packages/_server/spell-checker-config.schema.json, packages/_server/src/config/cspellConfig.ts
See: [SCM: Support input box spell checking · Issue #35571 · microsoft/vscode](https://github.com/microsoft/vscode/issues/35571#issuecomment-1195219643)
=> fix: Support spell checking commit message

.prettierignore, .prettierrc.json, docs/_includes/generated-docs/configuration.md, package.json, packages/_server/spell-checker-config.schema.json, packages/_server/src/config/cspellConfig.ts, packages/client/src/settings/languageIds.ts
=> fix: add `erlang` to default enabledLanguageIds

packages/_server/src/config/documentSettings.ts
=> fix: Update glob to match only files in workspace folders

packages/__utils/src/errors.ts, packages/__utils/src/file.ts, packages/client/package.json, packages/client/src/settings/configFileReadWrite.ts, packages/client/src/settings/fs.test.ts, packages/client/src/settings/fs.ts, packages/client/src/settings/settings.ts, packages/jest-mock-vscode-examples/package.json, yarn.lock
=> fix: Fix create config file

packages/client/src/settings/configRepository.ts, packages/client/src/settings/fs.ts
=> fix: Correctly format config files

packages/client/src/extension.ts
=> fix: extension crash

packages/_server/src/server.ts
=> fix: Log the entire error

README.md
Add Serbian to list of add-ons
=> Add Serbian to list of addons

modules/package.json, package.json, packages/_integrationTests/package.json, packages/_server/package.json, packages/_serverPatternMatcher/package.json, packages/_settingsViewer/package.json, packages/client/package.json, yarn.lock
=> fix: Update cspell

CONTRIBUTE.md
=> docs: add `yarn build` to CONTRIBUTE.md

docs/_includes/generated-docs/configuration.md, package.json, packages/_server/spell-checker-config.schema.json, packages/_server/src/config/cspellConfig/CSpellSettingsPackageProperties.ts
=> fix: fix typo

docs/_includes/generated-docs/configuration.md, package.json, packages/_server/spell-checker-config.schema.json, packages/_server/src/api/models/DiagnosticData.mts, packages/_server/src/codeActions.mts, packages/_server/src/config/cspellConfig/CSpellSettingsPackageProperties.mts, packages/_server/src/config/cspellConfig/SpellCheckerSettings.mts, packages/_server/src/config/cspellConfig/cspellConfig.mts, packages/_server/src/config/cspellConfig/cspellMergeFields.mts, packages/_server/src/config/cspellConfig/cspellMergeFields.test.mts, packages/_server/src/config/documentSettings.mts, packages/_server/src/validator.mts, packages/client/src/codeActions/actionSuggestSpellingCorrections.ts, packages/client/src/decorate.ts, packages/client/src/settings/configFields.ts
- fix: Improve decorations and suggestions
- fix: Adjust how settings are merged with CSpell
=> fix: Improve decorations and suggestions

package.json, packages/_integrationTests/src/extension.test.mts, packages/_server/spell-checker-config.schema.json, packages/_server/src/api/api.ts, packages/_server/src/api/apiModels.ts, packages/_server/src/config/cspellConfig/SpellCheckerSettings.mts, packages/_server/src/config/cspellConfig/configFields.mts, packages/_server/src/config/cspellConfig/index.mts, packages/_server/src/config/documentSettings.mts, packages/_server/src/config/sanitizeSettings.mts, packages/_server/src/lib/index.mts, packages/_server/src/server.mts, packages/client/src/autocomplete.mts, packages/client/src/client/DocumentConfigCache.mts, packages/client/src/client/client.mts, packages/client/src/client/index.mts, packages/client/src/client/server/server.ts, packages/client/src/client/server/serverSettings.ts, packages/client/src/commands.mts, packages/client/src/context.mts, packages/client/src/decorators/decorateIssues.mts, packages/client/src/extension.mts, packages/client/src/extensionRegEx/extensionRegEx.mts, packages/client/src/infoViewer/infoHelper.mts, packages/client/src/languageStatus.mts, packages/client/src/settings/DictionaryHelper.mts, packages/client/src/settings/configFields.mts, packages/client/src/settings/vsConfig.test.mts, packages/client/src/statusbar.mts
Reduce the size of the data sent between the client and server.
The entire configuration was being sent to the client from the server when only a few fields were needed.
=> fix: Reduce traffic volume between client/server

package.json, packages/_server/spell-checker-config.schema.json, packages/_server/src/config/cspellConfig/AppearanceSettings.mts, packages/_server/src/config/cspellConfig/SpellCheckerSettings.mts
=> fix: Change scope of decoration settings

website/package-lock.json
Fixes security warning. Note: the warning does not apply to the spell checker.
=> chore: Update website packages

packages/client/src/issueViewer/issueFilter.mts
#3445 hid too much. Keep issues related to open tabs.
=> fix: make sure issues in all tabs are visible

package.json, packages/_server/spell-checker-config.schema.json, packages/_server/src/config/cspellConfig/cspellConfig.mts
=> fix: remove typo

docs/_includes/generated-docs/commands.md, package.json, packages/_integrationTests/package.json, packages/_integrationTests/src/extension.test.mts, packages/_integrationTests/src/runTests.mts, packages/client/src/commands.mts, packages/client/src/issueViewer/issuesViewerByFile.mts, packages/client/src/issueViewer/unknownWordsViewer.mts, packages/client/src/webview/webview.mts, tsconfig.base.json, tsconfig.json, website/docs/auto_commands.md
VS Code has become picky about view names.
=> fix: Remove `.` from view names.

packages/client/src/extension.mts, packages/client/src/issueViewer/issuesViewerByFile.mts, packages/client/src/issueViewer/unknownWordsViewer.mts
Make sure the views can be registered as soon as possible. See: [vscode #224590](https://github.com/microsoft/vscode/issues/224590#issuecomment-2265674035)
=> fix: Register views as soon as possible.

packages/_integrationTests/src/extension.test.mts, packages/_integrationTests/src/helper.mts
This is a test to make sure untitled document keep working.
=> test: Add test for #3543

.vscode/launch.json, packages/_server/src/config/documentSettings.mts, packages/_server/src/config/urlUtil.mts, packages/_server/src/config/urlUtil.test.mts
=> fix: improve handling of untitled files

package.json
=> fix: Remove dot from title

packages/client/src/storage/mementoFile.mts, packages/webview-ui/src/App.svelte, packages/webview-ui/src/components/VscodeButton.svelte, packages/webview-ui/src/components/VscodeCheckbox.svelte, packages/webview-ui/src/components/VscodeLink.svelte, packages/webview-ui/src/components/VscodeTextField.svelte, packages/webview-ui/src/main.ts, packages/webview-ui/src/views/CSpellInfo.svelte, packages/webview-ui/src/views/HelloWorld.svelte, packages/webview-ui/src/views/Todo.svelte, packages/webview-ui/src/views/VSCodeComponents.svelte
=> fix: Fix Info Pane

packages/client/src/storage/mementoFile.mts
=> fix: Remove debug noise.

package-lock.json, packages/__utils/package.json, packages/__utils/src/uriHelper.test.mts, packages/__utils/src/uriHelper.ts, packages/_server/package.json, packages/_server/src/config/documentSettings.mts, packages/_server/src/config/urlUtil.mts, packages/client/src/applyCorrections.mts
=> fix: Fix issues with UNC

package.json, packages/_server/spell-checker-config.schema.json, packages/_server/src/config/cspellConfig/SpellCheckerSettings.mts
=> fix: Fix spelling issue

.vscodeignore, eslint.config.js, package-lock.json, package.json, packages/_integrationTests/src/ExtensionApi.mts, packages/_server/package.json, packages/_server/tsconfig.json, packages/_server/tsup.config.ts
Use `tsup` to build the extension server.
=> fix: Reduce the size of the Extension

package.json, packages/client/src/commands.mts
=> fix: Hide info from activity bar

package-lock.json, package.json, packages/_server/src/config/documentSettings.test.mts
Related to #3836
Removes the last of the defaults.
=> fix: Update dictionaries

packages/client/src/settings/DictionaryTarget.mts, packages/client/src/settings/configUpdaters.mts, packages/client/src/settings/wordList.mts, packages/client/src/settings/wordList.test.mts, samples/custom-dictionary/README.md, samples/custom-dictionary/words.txt
=> fix: improve how words are sorted

packages/_server/src/handleCheckDocumentRequest.ts, packages/client/src/decorators/traceDecorations.mts, packages/client/src/repl/cmdCheck.mts, packages/client/src/repl/cmdTrace.mts, packages/client/src/repl/repl.mts, samples/custom-dictionary/cspell.json, samples/custom-dictionary/dict.dic
=> fix: Make sure the repl check uses the right directory

package.json, packages/_server/spell-checker-config.schema.json, packages/_server/src/config/cspellConfig/SpellCheckerSettings.mts, packages/_server/src/config/cspellConfig/configFields.mts, packages/_server/src/config/cspellConfig/index.mts, packages/_server/src/server.mts, packages/_server/src/utils/analysis.mts, packages/client/src/extension.mts
=> fix: Add a setting to control notifications

packages/webview-ui/src/views/CSpellInfo.svelte
=> fix: Report when .gitignore blocks a file.
