client/README.md

Updated the README file to include documentation for the new "cSpell.spellCheckDelayMs" configuration setting, including it's default value.

Add README documentation for "spellCheckDelayMs" setting

---

server/src/DefaultSettings.ts

Thanks for this excellent extension!
Is there a reason why json shouldn't work with a default installation?

Add json to defaultSettings/enabledLanguageIds

---

server/package.json

Typescript 2.2.0 is in RC and npm is already downloading it based on the previous dependency version rules.
VSCode is currently using 2.1.5, so it seems to make sense to follow that version. 
Additionally the 2.2 compiler has a breaking change with lodash that prevents building spellchecker if tsc 2.2 is used.  cf.  https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14502
Once the lodash fix is merged and a new @types/lodash published, this commit can be reverted.

Pinning to Typescript 2.1.5

---

client/README.md

In readme there is a number of examples how words are processed.
One of them "srcCode" is an example of exact same rule as "camelCase" thus I think it might be simply removed to shorten README.

Removed redundant camelCase example in README

---

client/src/client/client.ts
client/src/util/uriHelper.ts

This PR adds support for [Visual Studio Live Share](https://aka.ms/vsls), and is the accompanying change to [this CSpell PR](https://github.com/Jason3S/cspell/pull/28). With this change in place, all developers that join a Live Share collaboration session, and have this extension installed, will be able to continue benefiting from the spell checking behavior they would expect (which could be really important for pairing/mentoring/etc. scenarios):
After [this CSpell PR](https://github.com/Jason3S/cspell/pull/28) was merged, it would obviously need to be published to NPM, and depending on the new version, [this dependency](https://github.com/Jason-Rev/vscode-spell-checker/blob/master/server/package.json#L16) would need to be updated. However, this change could still be made separately, …

Adding support for Visual Studio Live Share

---

README.md

Changed all instances of Las Angles to Los Angeles. This looks like an unintentional typo of L.A.

Potential typo, Las Angles -> Los Angeles

---

client/README.md
client/package.json
client/src/settings/languageIds.ts

[AsciiDoc](https://en.wikipedia.org/wiki/AsciiDoc) is a documentation format in the same vein as markdown and restructuredtext (both currently supported by default). Documentation, like [Pro Git 2](https://github.com/progit/progit2), the Git Book, are written in it. This pull request is to add it as supported out of the box.

Adding support for AsciiDoc out of the box

---

client/src/client/client.ts
client/src/util/uriHelper.ts

This is the corresponding PR for https://github.com/Jason3S/cspell/pull/31, and effectively reverts #191. As described in the CSPell PR, the reason for reverting this change is because we've enhanced Live Share to allow arbitrary language services to be remoted from the host to their guests, as opposed to relying on guests to also run them locally (e.g. spell checking). In this case, by ensuring that only the host runs spell checking (who would have access to `file` documents), it prevents a guest (who has access to `vsls` documents) from seeing duplicated diagnostics if they also have this extension installed.

[Live Share] Restricting language services to local files

---

packages/client/README.md

I started using this spellchecker as I was writing documentation in
reStructuredText and I noticed rst wasn't listed as an enabled file type.
I dug around to see how to enable the spellchecker for rst documents
however it seemed as though the spellchecker is actually enabled for
reStructuredText out of the box.
I thought it might be helpful to include it in the list of enabled file
types in the readme.

Add rst to the list of enabled file types

---

packages/client/package.json

Fixes #342.
This makes it so by default, only files under `.git/objects` are ignored instead of everything under `.git`.
I don't know if this is the best fix for the issue so I'd appreciate your feedback.

Ignore only git object files by default

---

README.md

While opening a pull request to add a term to the software terms dictionary, it took me a while to figure out which package does it belong to. So, I've updated the README file to include a link to the dictionaries package of cspell.
Thanks!

Add link to cspell's dictionaries package [README]

---

packages/client/src/settings/settings.ts

Hi!
The main cSpell package lists `.cspell.json` as one of the paths checked for the configuration file[0]. However the vscode plugin omits that filename, so sending this PR to add it.
Please let me know if anything else should be done here.
Thanks!
[0]: https://github.com/streetsidesoftware/cspell/tree/master/packages/cspell#customization

Add .cspell.json to paths checked for config file

---

packages/_server/spell-checker-config.schema.json
packages/_server/src/documentSettings.ts
packages/client/package.json
packages/client/src/util/uriHelper.ts

This PR simply adds support for the spell checker to run on files that are provided by the `gist` and `sftp` virtual file systems.
// CC @Jason3S

Adding Gist/SFTP support

---

packages/_server/src/server.ts
packages/client/src/commands.ts
packages/client/src/extension.ts
packages/client/src/settings/CSpellSettings.ts
packages/client/src/statusbar.ts

This is to hand a bug in the language-server that will not trigger settings changes if the value didn't exist when the server was started.

fix: Make sure to listen for all settings changes.

---

packages/_server/src/documentSettings.ts
packages/client/package.json

Indicate that `enableLanguageIds` is not deprecated.

Fix: enabled languages

---

packages/_server/src/WorkspacePathResolver.test.ts
packages/_server/src/WorkspacePathResolver.ts

New Resolver
- `.` => current workspace folder
- `~` => User Home
- `${root}` | `${workspaceRoot}` => workspace root
- `${workspaceFolder[:folder name]}` => workspace folder matching name.

fix: Adjust the workspace resolver paths

---

packages/client/package.json

Fixes:
- streetsidesoftware/vscode-cspell-dict-extensions#21
- streetsidesoftware/vscode-cspell-dict-extensions#35
- streetsidesoftware/vscode-cspell-dict-extensions#46
- streetsidesoftware/vscode-cspell-dict-extensions#50

Adds missing file extension to main entry point

---

packages/client/README.md

See https://github.com/streetsidesoftware/cspell-dicts/issues/271
Or, if this is still desired, maybe the extension should be updated and ownership transferred to `streetsidesoftware`

Don't link to outdated extension

---

packages/client/src/settings/languageIds.ts

Hi, this plugin is really helpful to me.
But it really took me a while to figure out why it didn't work in the julia programming language files. So I'd propose to add `julia` in the settings.
Thanks for your awesome work!

Add julia to languageIds.ts

---

README.md

The current definition of HexDigit is not very useful, since it will not match anything except at the beginning of a document.

fix: remove HexDigit from predefined patterns

---

cspell-words.txt
package.json

Explicitly turn off support for `virtualWorkspaces` and `untrustedWorkspaces` until further investigation is possible.
See #846 and #839.

fix: Turn off `virtualWorkspaces` and `untrustedWorkspaces`

---

fixtures/workspaces/yarn2/yarn2-test-med/custom-terms.txt
packages/_server/src/server.ts
packages/_server/src/utils/index.ts
packages/_server/src/utils/util.test.ts
packages/_server/src/utils/util.ts
packages/client/src/settings/CSpellSettings.ts
packages/client/src/settings/DictionaryHelper.ts
packages/client/src/settings/settings.ts

Make sure words are only split along word boundaries.

fix: #541 - Only split the selection on word boundaries

---

cSpell.json
packages/_server/jest.config.js
packages/_server/src/__snapshots__/commands.test.ts.snap
packages/_server/src/api.ts
packages/_server/src/clientApi.test.ts
packages/_server/src/codeAction.test.ts
packages/_server/src/commands.test.ts
packages/_server/src/commands.ts
packages/_server/src/config/configTargets.test.ts
packages/_server/src/config/configTargets.ts
packages/_server/src/config/vscode.config.test.ts
packages/_server/src/progressNotifier.test.ts
packages/_server/src/server.test.ts
packages/_server/src/server.ts

ConfigTarget is a structure that allows configuration change destinations to be sorted in preferred order.
The idea is to move the logic to the server, having it in one place.

dev: Create configTargets to allow sorted config changes

---

CONTRIBUTE.md
package.json
packages/client/src/context.ts

Give the option to create `cspell.json` if a
config file is not found in the workspace.

dev: give the option to create `cspell.json`

---

package.json
packages/_server/spell-checker-config.schema.json
packages/_server/src/config/cspellConfig.ts
packages/_server/src/server.ts
packages/_server/src/utils/analysis.test.ts
packages/_server/src/utils/analysis.ts
packages/client/src/settings/configFields.ts

Adds the following settings:
```typescript
interface SpellCheckerShouldCheckDocSettings {
/**
* The maximum line length
* @scope resource
* @default 1000
*/
blockCheckingWhenLineLengthGreaterThan?: number;
/**
* The maximum size of text chunks
* @scope resource
* @default 200
*/
blockCheckingWhenTextChunkSizeGreaterThan?: number;
/**
* The maximum average chunk of text size.
* A chunk is the characters between absolute word breaks.
* Absolute word breaks match: `/[\s,{}[\]]/`
* @scope resource
* @default 40
*/
blockCheckingWhenAverageChunkSizeGreatherThan?: number;
}
```

fix: Block checking of minified documents to prevent high-cpu usage.

---

package.json
packages/_server/spell-checker-config.schema.json
packages/_server/src/config/cspellConfig.ts
packages/client/src/commands.ts
packages/client/src/settings/DictionaryHelper.ts
packages/client/src/settings/configFields.test.ts
packages/client/src/settings/configFields.ts
packages/client/src/settings/configRepository.ts
packages/client/src/settings/index.ts

Have the right click spelling suggestions menu option and the Find Next/Previous Issue use the same suggestions menu.
@elazarcoh, Thank you for the help. I made a minor change.

fix: Make suggestions menu consistent

---

README.md
docs/index.md
packages/client/README.md

Related to [cspell documentation lists version as always 0.1 · Issue #1638](https://github.com/streetsidesoftware/cspell/issues/1638)

fix: Fix References to version "0.1"

---

packages/client/docs/settings.md
packages/client/src/commands.ts
packages/client/src/settings/CSpellSettings.test.ts
packages/client/src/settings/clientConfigTarget.ts
packages/client/src/settings/configRepository.ts
packages/client/src/settings/configRepositoryHelper.ts
packages/client/src/settings/index.ts
packages/client/src/settings/settings.test.ts
packages/client/src/settings/settings.ts
packages/client/src/settings/targetAndScope.test.ts
packages/client/src/settings/targetAndScope.ts

When adding / removing locales, the scope is either Global or Workspace.
Global - means it is possible to adjust any configuration.
Workspaces - means it is possible to adjust any configuration that is not Global.
-   Targets are presented from Locale to Global.
-   Targets _Inherit_ their values from Global to Local.
1. Only present targets that will have an impact.
1. If no targets will have an impact, then present any target that can be changed.
1. If there is only 1 target, then perform action without asking.
1. Only present targets that will have an impact.
1. If no targets will have an impact, do nothing.
1. If there is only 1 target, then perform action without asking.

fix: Fix add / remove locale from configuration

---

packages/client/docs/settings.md
packages/client/src/commands.ts
packages/client/src/settings/index.test.ts
packages/client/src/settings/index.ts
packages/client/src/settings/settings.base.ts
packages/client/src/settings/settings.enable.test.ts
packages/client/src/settings/settings.enable.ts
packages/client/src/settings/settings.locale.test.ts
packages/client/src/settings/settings.locale.ts
packages/client/src/settings/settings.test.ts
packages/client/src/settings/settings.ts
packages/client/src/settings/settings.types.ts

Fix: #1289 
There are currently two different target scopes (Workspace and Global). These are really max level of influence.
The goal of the Toggle is to turn on / off the spell checker in a intuitive and predictable way. In other words:
> If the spell checker is currently off for the file I have open, I want it on and vice versa.
The logic to the Toggler is as follows:
-   Find the most local configuration with the `enable` value set.
-   Remove it if it will become the same as the inherited value otherwise set it to the negation.
Having a scope of Workspace prevents the Global value from being updated, but the rest of the logic is the same.

fix: Fix Toggle Enable Spell Checker 

---

packages/client/src/commands.ts
packages/client/src/context.ts
packages/client/src/infoViewer/infoHelper.ts
packages/client/src/infoViewer/infoView.ts
packages/client/src/settings/DictionaryHelper.ts
packages/client/src/settings/configRepositoryHelper.ts
packages/client/src/settings/configTargetHelper.ts
packages/client/src/settings/mappers/configTarget.ts
packages/client/src/settings/vsConfig.ts
packages/client/src/util/uriHelper.ts

Fix: #1341
VS Code seems to be very sensitive to the class instance that created a
URI when accessing the Configuration.

fix: Make sure the VS Code instance of Uri is used

---

docs/_includes/generated-docs/commands.md
package.json
packages/client/src/commands.ts
packages/client/src/statusbar.ts

Have the status bar `enable` spelling use `cSpell.enableForGlobal`.
Fix #1289

dev: Have the general toggle command change nearest setting

---

packages/_server/src/config/documentSettings.ts
packages/client/src/client/client.ts
packages/client/src/settings/vsConfig.ts
packages/client/src/util/documentUri.ts

fix: #1353
Add a workaround to address the issue that VS Code Config cannot cope with Notebook documents. See: [WorkspaceConfiguration update fails if TextDocument is a Notebook · Issue #134103 · microsoft/vscode](https://github.com/microsoft/vscode/issues/134103)

fix: Fix adding words in Notebooks

---

docs/_includes/generated-docs/configuration.md
package.json
packages/_server/spell-checker-config.schema.json
packages/_server/src/config/cspellConfig.ts
packages/client/src/autocomplete.ts
packages/client/src/settings/configFields.ts

fix: #1536 
There is no real fix, this fix allows the option to be turned off.
The real fix would need to take place in VS Code.

fix: Put cspell autocompletion behind a configuration setting.

---

docs/_includes/generated-docs/configuration.md
package.json
packages/__utils/src/util.test.ts
packages/__utils/src/util.ts
packages/_server/spell-checker-config.schema.json
packages/_server/src/config/configTargetsHelper.ts
packages/_server/src/config/cspellConfig.ts
packages/_server/src/config/documentSettings.ts
packages/client/src/client/client.ts
packages/client/src/extension.ts
packages/client/src/infoViewer/infoHelper.ts
packages/client/src/infoViewer/infoView.ts
packages/client/src/statusbar.ts

Make sure the status bar and the configuration page
reflects changes to the configuration.
- Do not show `readonly` configurations.
- Move enableFileTypes

fix: Configuration changes should be responsive

---

docs/_includes/generated-docs/configuration.md
package.json
packages/_server/spell-checker-config.schema.json
packages/_server/src/config/cspellConfig.ts

fix: remove duplicate definition of `enableFiletypes`

---

docs/_includes/generated-docs/configuration.md
package.json
packages/_server/spell-checker-config.schema.json
packages/_server/src/config/cspellConfig.ts
packages/_server/src/config/documentSettings.test.ts
packages/_server/src/config/documentSettings.ts
packages/_server/src/server.ts
packages/client/src/settings/configFields.ts

fix: #1927 
fix: #1935 - `checkOnlyEnabledFileTypes: false` gets it close. There are still differences for performance and personal preference reasons. It is still possible to get the extension to not check a file type.
```json
"cSpell.checkOnlyEnabledFileTypes": false,
"cSpell.enableFiletypes": ["!java"]
```
**Alternate method**
```json
"cSpell.enableFiletypes": ["*", "!java"]
```

feat: Add `checkOnlyEnabledFileTypes` option

---

fixtures/workspaces/yarn2/yarn2-test-med/package.json
fixtures/workspaces/yarn2/yarn2-test-science/package.json
package.json
packages/_integrationTests/package.json
packages/_server/package.json
packages/_serverPatternMatcher/package.json
packages/client/package.json
yarn.lock

Note: this should have no real impact on the Extension since it is already running on Node 16.

dev: Upgrade to CSpell 6

---

README.md

Hi
I'm searching for a while howto be able to declare per-file language and finally found the answer in #676.
I don't know why it's not documented in [cSpell documentation](https://cspell.org/configuration/document-settings/#in-document-settings). I probably would make a PR there too

doc: README - Add "locale" in-document setting

---

packages/jest-mock-vscode/src/vscode/WorkspaceConfiguration.ts

Address:
> This assignment may alter Object.prototype if a malicious '__proto__' string is injected.

fix: Make sure `__proto__` cannot be overwritten.

---

fixtures/workspaces/dictionaries/remote/README.md
fixtures/workspaces/dictionaries/remote/cspell.json
fixtures/workspaces/dictionaries/remote/test.txt
packages/_server/src/utils/fileWatcher.ts

CSpell 6.2.2 supports using remote dictionaries. Fix an issues with the extension that prevent reading remote dictionaries.
Related to #2044

feat: Support remote dictionaries

---

packages/_server/src/config/documentSettings.ts

👋🏻 I am a member of the VS Code team and I have been looking at a feature request (https://github.com/microsoft/vscode/issues/35571) to enable spell check for the SCM input field. I have validated that extension authors already have all the necessary APIs in place to access the text document that is associated with the SCM input field.
Looking at the code of this particular extension, the only blocker at the moment to enable this functionality is due to the fact that the `vscode` scheme is in the list of clocked schemes. Removing it from there, one case use the existing settings to configure the extension to provide spell checking capabilities to the SCM input field.

Remove "vscode" from the list of blocked schemes

---

cspell-words.txt
docs/_includes/generated-docs/configuration.md
package.json
packages/_server/spell-checker-config.schema.json
packages/_server/src/config/cspellConfig.ts

Related to [SCM: Support input box spell checking · Issue #35571 · microsoft/vscode](https://github.com/microsoft/vscode/issues/35571)

fix: Add default support for `vscode` `scminput` files.

---

docs/_includes/generated-docs/configuration.md
package.json
packages/_server/spell-checker-config.schema.json
packages/_server/src/config/cspellConfig.ts

Add it back when [Support markers for the SCM input document · Issue #155282 · microsoft/vscode](https://github.com/microsoft/vscode/issues/155282) is ready.

fix: Turn off `scminput` until VS Code is ready

---

docs/_includes/generated-docs/configuration.md
package.json
packages/_server/spell-checker-config.schema.json
packages/_server/src/config/cspellConfig.ts
packages/client/src/context.ts
packages/client/src/settings/configFields.ts

- Move all spelling commands into a `Spelling` submenu
- Add a setting to show suggestions in the context menu: `cSpell. showSuggestionsLinkInEditorContextMenu`
- Adjust order of the spelling commands

feat: Move Spelling Menu items into a submenu

---

docs/_includes/generated-docs/configuration.md
package.json
packages/_server/spell-checker-config.schema.json
packages/_server/src/config/cspellConfig.ts
packages/client/src/settings/configFields.ts
packages/client/src/settings/configRepository.ts

fixes #2151
- Added a new option `autoFormatConfigFile` (default: `false`)
- Support formatting CSpell configuration files when updating them.
When `autoFormatConfigfile` is `true` the following steps are taken:
1. the file is saved if it is open in an editor
2. the file is updated
3. the file is formatted and saved.

feat: Format CSpell Configuration on Update

---

package.json
samples/scss/example.css
samples/scss/example.sass
samples/scss/example.scss

fix: #2268
- Turn on rename provider in PHP. It no-longer crashes.
- Turn off rename provider for CSS and SCSS. It does the wrong thing.

fix: change `fixSpellingWithRenameProvider` defaults

---

packages/_server/src/utils/analysis.ts

fix: Correct error message for Maximum Word Length Exceeded

---

packages/_server/src/codeActions.ts
packages/_server/src/utils/position.ts
packages/_server/src/utils/range.ts

- Do not show code actions if the selection is multiple words.
This fixes the issue where spelling suggestions hide refactoring and other Code Actions.
- fixes #2482
- Start the process to support `@cspell/eslint-plugin` by providing the ability to add to dictionary.
- If an issues is handled by both ESLint `@cspell/spellchecker` and this extension, defer to ESLint.

fix: Do not show duplicate actions.

---

fixtures/workspaces/auto-fix/common-mistakes.md
package.json
packages/client/src/commands.ts

fix: Use Workspace edits for making fixes.

---

package.json
packages/client/src/context.ts

fix: Do not show context menu if `editorReadonly`

---

docs/_includes/generated-docs/configuration.md
package.json
packages/_server/spell-checker-config.schema.json
packages/_server/src/config/cspellConfig/CSpellSettingsPackageProperties.mts
packages/_server/src/config/cspellConfig/SpellCheckerSettings.mts
packages/_server/src/config/cspellConfig/cspellConfig.mts
packages/_server/src/config/cspellConfig/cspellMergeFields.mts
packages/_server/src/config/cspellConfig/cspellMergeFields.test.mts
packages/_server/src/config/documentSettings.mts
packages/_server/src/config/documentSettings.test.mts
packages/_server/src/server.mts
packages/client/src/settings/configFields.ts

One of the common issues is that the results seen in the extension do not match the results seen by the command line tool.
This is often due to settings in VSCode influencing the extension results.
- `mergeCSpellSettings` - allows more control over what settings are passed to `cspell`. By default, if a cspell config file is found, settings that might impact the result are not sent.

feat: Control which settings are passed to cspell

---

docs/_includes/generated-docs/configuration.md
fixtures/workspaces/jupyter/.vscode/settings.json
fixtures/workspaces/jupyter/cspell.json
fixtures/workspaces/jupyter/getting-started/README.md
fixtures/workspaces/jupyter/getting-started/sample.ipynb
fixtures/workspaces/jupyter/hello.py
package.json
packages/_server/spell-checker-config.schema.json
packages/_server/src/config/cspellConfig/SpellCheckerSettings.mts
packages/_server/src/config/cspellConfig/cspellConfig.mts
packages/_server/src/validator.mts
packages/client/src/decorate.ts
packages/client/src/extension.ts
packages/client/src/extensionRegEx/extensionRegEx.ts
packages/client/src/settings/configFields.ts

Fixes: #2885, #186 
Related to: #872, #1535, #144, #128
- Support custom decorators
- Support setting a different diag level for flagged words
When the `diagnosticLevel` is set to Hint, allow for custom text decoration and colors in the ruler.

feat: support custom decorators

---

docs/_includes/generated-docs/configuration.md
package.json
packages/_server/spell-checker-config.schema.json
packages/_server/src/config/cspellConfig/SpellCheckerSettings.mts
packages/_server/src/config/cspellConfig/cspellConfig.mts
packages/_server/src/config/docUriHelper.mts
packages/_server/src/validator.mts
packages/client/src/decorate.ts
packages/client/src/settings/configFields.ts

Features:
- Add light/dark theme support for decorations
- Add `diagnosticLevelSCM` setting to allow for showing issues differently while editing the commit message.

feat: Add light/dark theme support

---

package.json
packages/_server/src/config/documentSettings.mts
packages/_server/src/server.mts
packages/_server/src/vfs/CSpellFileSystemProvider.mts
packages/client/src/extension.ts
packages/client/src/settings/CSpellSettings.ts

Everytime a cspell config file was opened, the configuration was reset causing all the dictionaries to reload.

fix: reduce reloading when opening a cspell config

---

README.md

In many codebases, the Problems panel will quickly fill up with issues that are not misspellings, but words relating to code. These make it more difficult to spot 'actual' problems such as linting or type-checking.
I have been using the VS Code extension for a long time, but only recently learned how to change this behaviour. (I initially searched the README for the word 'Problems').
Judging from the votes [on this StackOverflow post](https://stackoverflow.com/a/72723985/119822), other people would also find this useful to know about.
I have copied the configuration details from https://streetsidesoftware.com/vscode-spell-checker/docs/configuration/#cspelldiagnosticlevel

Document `diagnosticLevel` in README

---

CONTRIBUTE.md

VSMarketplaceBadges is migrating to a new platform, please change the URL.
https://vsmarketplacebadge.apphb.com -> https://vsmarketplacebadges.dev
https://github.com/cssho/VSMarketplaceBadge -> https://github.com/cssho/VSMarketplaceBadges

Visual Studio Marketplace Badge Service URL Change

---

.github/workflows/manual-publish.yml
.github/workflows/release-please.yml
release-please-config.json

Adjust the workflows to prevent accidental publishing of alpha versions.
Note: The "Test Exit" is still in to workflow until we have tried to publish the first alpha release.

chore: protect against publishing alpha versions

---

.github/workflows/test.yml
docs/_includes/generated-docs/commands.md
package.json
packages/_integrationTests/src/extension.test.mts
packages/client/src/commands.ts
packages/client/src/context.ts
packages/client/src/decorators/decorateIssues.ts
packages/client/src/decorators/traceDecorations.ts
packages/client/src/extension.ts
packages/client/src/extensionApi.ts

- Rename `disableCurrentLanguage` to `disableCurrentFileType`
- Rename `enableCurrentLanguage` to `enableCurrentFileType`
- Add `toggleVisible`
- Add `show`
- Add `hide`

fix: Commands

---

packages/_server/src/config/configTargetsHelper.mts
packages/client/src/promptUser.ts

It looks like VSCode started sending the Uri when selecting a menu item, this broke adding words.

fix: issue when adding words to config

---

docs/_includes/generated-docs/configuration.md
package.json
packages/_integrationTests/src/extension.test.mts
packages/_integrationTests/src/helper.mts
packages/_integrationTests/testFixtures/.vscode/settings.json
packages/_server/spell-checker-config.schema.json
packages/_server/src/config/cspellConfig/AppearanceSettings.mts
packages/_server/src/config/cspellConfig/SpellCheckerSettings.mts
packages/client/src/issueViewer/issuesViewerByFile.ts

- merge vscode settings by default, this is to preserve existing behavior.
- Use the Spell Checker's decorator by default.
- Use `Hint` to hide issues from the Problems Pane

fix: Adjust the default settings

---

docs/_includes/generated-docs/configuration.md
package.json
packages/_server/spell-checker-config.schema.json
packages/_server/src/config/cspellConfig/SpellCheckerSettings.mts
packages/_server/src/config/documentSettings.mts

Related to (#1554 Live Share Comment)[https://github.com/streetsidesoftware/vscode-spell-checker/issues/1554#issuecomment-1985273705]

fix: Add `vsls` to schemes to support Live Share

---

tsconfig.json

VS Code was listing 1000s of issues in the problems pane  because it was trying to "compile" all JavaScript files in place.

chore: Reduce false positive errors in VS Code.

---

docs/_includes/generated-docs/configuration.md
package.json
packages/__utils/src/uriHelper.ts
packages/_server/spell-checker-config.schema.json
packages/_server/src/config/cspellConfig/SpellCheckerSettings.mts

This enables spell check in VS Code's comment editors (commonly used while reviewing PRs). Depends on https://github.com/microsoft/vscode/pull/209512

Adds support for spell checking comment editors

---

packages/_server/src/DocumentValidationController.mts
packages/_server/src/utils/breakTextAtLimit.mts
packages/_server/src/utils/breakTextAtLimit.test.mts

When the "limit" is reached for large documents, the spell checker could just split mid word, causing false issues. This fix makes sure the text is limited to the last full word.

fix: Fix word break issue with large documents

---

cspell.config.yaml
docs/_includes/generated-docs/commands.md
docs/_includes/generated-docs/configuration.md
package.json
packages/_server/spell-checker-config.schema.json
packages/_server/src/config/cspellConfig/AppearanceSettings.mts
packages/_server/src/config/cspellConfig/SpellCheckerSettings.mts
packages/_server/src/config/cspellConfig/cspellConfig.mts
packages/_server/src/server.mts
packages/client/src/configWatcher.mts
packages/client/src/decorators/decorateIssues.mts
packages/client/src/extension.mts
packages/client/src/settings/configFields.mts
packages/client/src/statusbar.mts

Because of the custom decorators in v4, it is possible to control when issues are displayed.
v4 comes with a command to show/hide issues. This is different than the enable/disable command. That command turns the spell checker on/off, almost like shutting it down and restarting it.
Added a couple of settings:
```ts
export interface SpellCheckerBehaviorSettings {
/**
* Control how spelling issues are displayed while typing.
* See: `#cSpell.revealIssuesAfterMS#` to control when issues are revealed.
* @title Hide Issues While Typing
* @scope machine
* @since 4.0.0
* @default "Word"
* @enumDescriptions [
*  "Show issues while typing",
*  "Hide issues in the current word",
*  "Hide issues on the line",
*  "Hide all issues in the document"]
*/
hideIssuesWhileTyping?: 'Off' | 'Word' | 'Line' | …
```

feat: Hide spelling issues while typing.

---

docs/_includes/generated-docs/configuration.md
package.json
packages/_integrationTests/src/extension.test.mts
packages/_server/spell-checker-config.schema.json
packages/_server/src/config/cspellConfig/AppearanceSettings.mts
packages/_server/src/config/cspellConfig/SpellCheckerSettings.mts
packages/_server/src/config/cspellConfig/cspellConfig.mts
packages/_server/src/config/docUriHelper.mts
packages/_server/src/server.mts
packages/_server/src/validator.mts
packages/client/src/decorators/decorateIssues.mts
packages/client/src/diags.mts
packages/client/src/extension.mts
packages/client/src/languageStatus.mts
packages/client/src/quickMenu.mts
packages/client/src/settings/configFields.mts
packages/client/src/statusbar.mts

- All issues are now collected on the client side.
- The client controls if issues are shown by VS Code or custom.
- It is possible to force VS Code rendering by scheme
- It is possible to toggle the spelling display by command.
- Rename `decorateIssues` to `useCustomDecorations`
- Remove `diagnosticLevelSCM` replaced with `doNotUseCustomDecorationForScheme`
- Added `doNotUseCustomDecorationForScheme` to control rendering by scheme.

fix: change the approach to custom decorations

---

packages/client/src/repl/formatPath.mts

Remove the `./` prefix from the file path when reporting. This makes it possible to open links to files from within the REPL terminal.

fix: REPL - remove `./` from rel path

---

packages/client/src/repl/cmdCheck.mts

- Collapse the checking file lines
- Add a 10 file read-ahead to improve the throughput when checking files.

fix: Improve the REPL Check output

---

packages/_server/src/config/documentSettings.mts

It is not possible to calculate the relative URL of an `untitled` scheme.
fixes #3535

fix: Do not glob match against `untitled:Untitled*`

---

package.json
packages/_server/spell-checker-config.schema.json
packages/_server/src/api/apiModels.ts
packages/_server/src/config/cspellConfig/SpellCheckerSettings.mts
packages/_server/src/config/cspellConfig/configFields.mts
packages/_server/src/config/cspellConfig/cspellConfig.mts
packages/_server/src/config/documentSettings.mts
packages/_server/src/server.mts
packages/_server/src/test/test.api.ts
packages/client/src/client/client.mts
packages/client/src/client/server/server.mts
packages/client/src/infoViewer/infoHelper.mts
packages/client/src/languageStatus.mts
packages/webview-api/src/models/settings.ts
packages/webview-ui/src/views/CSpellInfo.svelte

The spell checker incorrectly showed that the spell checker was enabled for a file when it actually was not.

fix: Make sure the disabled status is shown

---

cspell-words.txt
packages/__utils/src/EventEmitter/index.mts
packages/__utils/src/EventEmitter/pipe.mts
packages/__utils/src/EventEmitter/types.mts
packages/client/src/applyCorrections.mts
packages/client/src/decorators/decorateIssues.mts
packages/client/src/di.mts
packages/client/src/extension.mts
packages/client/src/statusbar/languageStatus.mts
packages/client/src/storage/EventLog.mts
packages/client/src/storage/EventLogger.mts
packages/client/src/storage/context.mts
packages/client/src/storage/globalState.mts
packages/client/src/storage/index.mts
packages/client/src/storage/memento.mts
packages/client/src/storage/mementoFile.mts
packages/client/src/storage/mementoMem.mts
packages/client/src/storage/storage.mts

To improve the user experience, we want to start logging word replacements.
The idea is to move more recently used words to the top of the list.
This PR only logs the event. The code to apply the logic will come later.

fix: Log word replacements

---

README.md

"yml" appears to be an invalid ID since https://github.com/streetsidesoftware/vscode-spell-checker/commit/e169d6412c63afc2012c47f44418924c9d65e5f9
Hope it's alright 👌

Fix the yaml language ID in readme

---

package.json
packages/_server/spell-checker-config.schema.json
packages/_server/src/config/cspellConfig/FileTypesAndSchemeSettings.mts
packages/client/src/settings/languageIds.ts
website/docs/configuration/auto_files-folders-and-workspaces.md

This is an attempt to fix #2409, following the example changes from pull request: #2133.
Now, the `al` language has been added to the list of enabledLanguageIds.

fix: add al to default enabledLanguageIds

---

packages/_server/src/utils/analysis.mts

The links pointing to the setting which is responsible for blocking the file from being spell checked are broken.
Adding the missing `/performance` part of the url respectively fixes the issue.

fix: adjust broken links in blocked file hints

---

package.json
packages/_server/spell-checker-config.schema.json
packages/_server/src/config/cspellConfig/AppearanceSettings.mts

The transition to custom decorations has led to feedback that the yellow squiggly is too intrusive and can be mistaken for actual code diagnostics (#3798).
Proposing less intrusive defaults that are similar to the prior appearance and also leverage the new "dotted" appearance to clearly distinguish this from other diagnostics.  These values should look fine in either light or dark mode.
Light mode example:
Dark mode example:

Adjust default color and style for spelling error decorations

---

package.json
packages/_server/spell-checker-config.schema.json
packages/_server/src/config/cspellConfig/AppearanceSettings.mts
packages/_server/src/config/cspellConfig/SpellCheckerSettings.mts

To make it clear, that diagnostic level is only used when `cSpell.useCustomDecorations` is false.
Related to #3798

fix: Change the description of `diagnosticLevel`

---

packages/_server/src/config/docUriHelper.mts
packages/client/src/storage/mementoFile.mts

Change the way vscode-notebook-cell scheme is converted to a file scheme.
fixes #3787
fixes #3819

fix: Support vscode-notebook-cell in containers

---

package.json
packages/_server/spell-checker-config.schema.json
packages/_server/src/DocumentValidationController.mts
packages/_server/src/SuggestionsGenerator.mts
packages/_server/src/api/apiModels.ts
packages/_server/src/codeActions.mts
packages/_server/src/config/WorkspacePathResolver.mts
packages/_server/src/config/WorkspacePathResolver.test.mts
packages/_server/src/config/configTargetsHelper.mts
packages/_server/src/config/cspellConfig.test.mts
packages/_server/src/config/cspellConfig/SpellCheckerShouldCheckDocSettings.mts
packages/_server/src/config/cspellConfig/configFields.mts
packages/_server/src/config/cspellConfig/cspellConfig.mts
packages/_server/src/config/cspellConfig/cspellMergeFields.mts
packages/_server/src/config/cspellConfig/index.mts
packages/_server/src/config/customDictionaries.mts
packages/_server/src/config/customDictionaries.test.mts
packages/_server/src/config/documentSettings.mts
packages/_server/src/config/documentSettings.test.mts
packages/_server/src/config/extractEnabledFileTypes.mts
packages/_server/src/config/sanitizeSettings.mts
packages/_server/src/config/vscode.config.test.mts
packages/_server/src/server.mts
packages/_server/src/suggestionsServer.mts
packages/_server/src/utils/analysis.mts
packages/_server/src/validator.mts
packages/_server/src/vfs/CSpellFileSystemProvider.mts
packages/client/src/commands.mts

A while ago, VS Code changed editor and schema for editing `settings.json` and `keybindings.json` files. This change has caused the spell checker to report on issues it did not in the past.
This PR will ignore files of the form:
- `vscode-userdata:/**/settings.json`
- `vscode-userdata:/**/keybindings.json`
Related to #3581, #3542, https://github.com/streetsidesoftware/vscode-spell-checker/issues/3542#issuecomment-2511826418 , #3158.

fix: Make sure VS Code files are not spell checked

---

.github/workflows/release-mark-prerelease.yml
.github/workflows/release-please.yml

Make sure published releases are marked as `pre-release` when the `package.json` has `prerelease: true`.
fixes #3974
related to #3775

chore: Mark `pre-release` versions

---

packages/client/src/issueViewer/issuesViewerByFile.mts
packages/client/src/issueViewer/unknownWordsViewer.mts

The ellipse implied an ongoing action, as if spell check had not completed, even when it had.

Remove ellipse from "No issues found."

---

packages/__utils/src/uriHelper.test.mts
packages/__utils/src/uriHelper.ts
samples/custom-dictionary/.vscode/settings.json
samples/custom-dictionary/長いファイル名前.md

fix: decode file names before displaying them.

---

packages/_server/src/server.mts

fix: Remove `enabledLanguageIds` imported from cspell-lib

---

packages/client/src/commands.mts

To only show the extension settings user should pass the query in the format: `@ext:<publisher>.<name>`

fix: handle opening of settings is better way

---

package-lock.json
package.json

Accidentally running `pnpm` or `yarn` can lead to unexpected results.

chore: Prevent pnpm and yarn from being used.

---

package.json

The purpose of the command was to show on the problems panel, but filter doesn't work as expected. Remove for now.
fixes #4288

fix: Remove eye icon from title bars

---

package-lock.json
packages/_integrationTests/src/logger.mts
packages/_server/src/codeActions.mts
packages/_server/src/utils/debounce.test.mts
packages/_server/src/utils/fileWatcher.mts
packages/_serverPatternMatcher/package.json
packages/_serverPatternMatcher/src/PatternMatcher.mts
packages/_serverPatternMatcher/src/server.mts
packages/_serverPatternMatcher/tsdown.config.ts
packages/client/src/commands.mts
packages/client/src/extensionRegEx/extensionRegEx.mts
packages/client/src/settings/DictionaryTarget.mts
packages/client/src/util/errors.ts

The regexp checker fails on large documents.
This is caused by how data is moved between worker threads.
fixes #4615

fix: Regexp Checker blows up on large docs

---

fixtures/workspaces/unknown-words/.vscode/settings.json
package.json
packages/_server/spell-checker-config.schema.json
packages/_server/src/config/cspellConfig/AppearanceSettings.mts
packages/_server/src/config/cspellConfig/SpellCheckerSettings.mts
packages/_server/src/validator.mts

The default of `undefined` got turned into a string causing issues with the reporting.

fix: reportUnknownWords caused reporting issues
